CREATE TABLE IF NOT EXISTS PRODUCT (
    ID VARCHAR(36) PRIMARY KEY,
    NAME VARCHAR(100),
    Description VARCHAR(100),
    Price DECIMAL(20,4),
    Stock INT, 
    IsActive BOOLEAN DEFAULT TRUE,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    CreatedBy VARCHAR(50),
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UpdatedBy VARCHAR(50)
);